name: Tests

on: [push, pull_request]

jobs:
 ci:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        moodle-branch: ['master', 'MOODLE_311_STABLE', 'MOODLE_310_STABLE', 'MOODLE_39_STABLE']
        php: ['7.4']
        database: ['mysqli']

    name: ${{ matrix.moodle-branch }}  php ${{ matrix.php }}

    steps:
      - name: checkout moodle
        uses: actions/checkout@v2
        with:
          repository: moodle/moodle
          path: moodle
          ref: ${{ matrix.moodle-branch }}

      - name: checkout plugin
        uses: actions/checkout@v2
        with:
          path: moodle/local/aws

      - name: setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, gd, zip
          tools: composer, phpmd, phpcbf, phpcpd, psalm, phpcs

      - name: checkout moodle-plugin-ci
        uses: actions/checkout@v2
        with:
          repository: moodlehq/moodle-plugin-ci
          path: ci

      - name: composer
        run: |
           composer install
           echo "$(cd bin; pwd)" >> $GITHUB_PATH
           echo "$(cd vendor/bin; pwd)" >> $GITHUB_PATH
           sudo locale-gen en_AU.UTF-8
           cp ../moodle/.github/workflows/config-template.php ../moodle/config.php
           mkdir ../moodledata
        working-directory: ci

      - name: phplint
        run: moodle-plugin-ci phplint local/aws
        working-directory: moodle

      - name: phpcpd
        run: moodle-plugin-ci phpcpd local/aws
        working-directory: moodle

      - name: phpmd
        run: moodle-plugin-ci phpmd local/aws
        working-directory: moodle

      - name: codechecker
        run: moodle-plugin-ci codechecker local/aws
        working-directory: moodle

      - name: validate
        run: moodle-plugin-ci validate local/aws
        working-directory: moodle

      - name: phpdoc
        run: moodle-plugin-ci phpdoc local/aws || true
        working-directory: moodle
        env:
          dbtype: dbtype: ${{ matrix.database }}

      - name: savepoints
        run: moodle-plugin-ci savepoints local/aws
        working-directory: moodle

      - name: mustache
        run: moodle-plugin-ci mustache local/aws
        working-directory: moodle

      - name: grunt
        run: moodle-plugin-ci grunt local/aws || true
        working-directory: moodle
